### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by jeffscottward** [project-douglas/epm#23]
Can we rename the description to be specific to Eris? I'm intending to release an Ethereum native NPM like tool :)

**Comment by compleatang** [comment]
what do you have in mind? 

this tool was not eris specific but rather was built for ethereum, although it hasn't been maintained recently. if you're just looking for the namespacing on ruby gems how about ethereum-pm? 

i do intend to retain the epm namespacing on ruby gems, for the record. as i would like to revitalize this tool in the coming months and refactor for updated compilation and deployment issues on eris, mint, and eth.

**Comment by jeffscottward** [comment]
Not interested in ruby gems. 
My interest lies in `NPM` and the javascript eco-system. 

I want to bring the Node.js community into the contract creation space and to do that I want to have an package manager archetype this is as easy to use and social as NPM/Github. 

I'm dreaming of a `contracts.json` much like `package.json`. 
Given that solidity is javascript-esque I think its a great on-ramp.

I even have a Solidity logo similiar to Javascripts ready to go :). Thoughts?

**Comment by compleatang** [comment]
That sounds great! Perhaps take a look at sunit as Andreas has worked on this as well -- would be good to collaborate we think.

We don't have the `epm` namespace on `npm` though: [see here](https://www.npmjs.com/package/epm), so am not sure what renaming this repository would accomplish...?

**Comment by jeffscottward** [comment]
The top description says: Ethereum Package Manager --> https://epm.io  which actually points to eris's website, so my ask was basically to not just rename the repo, but the tool itself as well as the description, towards being eris-pm.

**Comment by jeffscottward** [comment]
and I wouldn't build this inside of NPM it would be a fork of NPM called EPM. With the exact description you have as "Ethereum Package Manager" - branded totally to/for ethereum.

**Comment by jeffscottward** [comment]
I want to have an package manager that looks to ethereum as the baseline with the apprioate acryonym for the tool. Eris and other would point to that as the main package management tool. I dont want to have a fragmented PM ecosystem

**Comment by compleatang** [comment]
I'm happy to add deprecated to the description to avoid confusion via github searches and remove the link to the epm.io domain. But I don't see how this repo's name or its presence on github affects your ability to build and distribute the tool you're describing. This tool doesn't work with our platform at Eris. Admittedly, it doesn't work with current Ethereum either.

`Eris and other would point to that as the main package management tool.` -> What are you talking about? (genuine question, not trolling) 

If you're building a branded tool specific to Ethereum then that tool would be branded for and limited to Ethereum's chain. If you're looking to build a smart contracts package manager focused on managing contract packages for any EVM-capable chain that's a different matter. We'd certainly be happy to talk about how we could assist and collaborate on the latter effort if that was indeed your intention.

**Comment by jeffscottward** [comment]
> Eris and other ethereum based platform would point to that as the main package management tool.
Sorry, should really say `contract management` tool. So ECM. Was just defaulting to NPM verbage.

But yea, you made a good point below for the latter.
How about an SCM or SCPM? 
It would be for all smart contract platforms :).

Note: I'm just a front-end ui guy just trying to evangelize for a "standard" of sorts. 
Wouldn't know how to really go about this. I definitely could hook you up with one of our teams to get this rolling though. :+1:

**Comment by compleatang** [comment]
:+1: Great. SCM is shorter for sure, although I'm generally bad with names. We agree that having a simple, approachable tool will assist new-comers, something that all the projects in the space should care about. 

Either way, have folks hook up with @androlo as he's the one working on the node/solidity stuff for us. 

Have made the changes to the repo description to reduce any confusion going forward.

**Comment by jeffscottward** [comment]
Great! Excited for this!

**Comment by compleatang** [comment]
Perfect. Closing for now. Feel free to reopen if needed.
